      # PyTorch Mobile PR builds (use linux host toolchain + mobile build options)
      - pytorch_linux_build:
          name: pytorch_linux_xenial_py3_clang5_mobile_build
          requires:
            - setup
          build_environment: "pytorch-linux-xenial-py3-clang5-mobile-build"
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-asan:a8006f9a-272d-4478-b137-d121c6f05c83"
      - pytorch_linux_build:
          name: pytorch_linux_xenial_py3_clang5_android_ndk_r19c_mobile_code_analysis
          requires:
            - setup
          build_environment: "pytorch-linux-xenial-py3-clang5-android-ndk-r19c-mobile-code-analysis"
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:a8006f9a-272d-4478-b137-d121c6f05c83"
