name: PyTorch Probot
on:
  issues:
    types: [opened, labeled, unlabeled]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, labeled, unlabeled]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: PyTorch Probot
    steps:
      - uses: pytorch/pytorch-probot@releases/v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
